# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ruby_on_skis}
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Daniel P. Zepeda"]
  s.date = %q{2010-03-21}
  s.default_executable = %q{ruby_on_skis}
  s.description = %q{  This is the real deal! Download and Install away! 

  Ruby on Skis provides a template for your wxRuby project. 
  The template provides a directory structure, a set of Rakefiles to manage, and most importantly, 
  to _package_ your Ruby application for distribution as a standalone program. It also includes an environment 
  to get the application running and provide basic services to the program code. For now, the template only 
  supports packaging for Mac OSX -and Windows-, although various flavors of Linux should be easily 
  accommodated and are planned for the future.

  Note: Windows support has been removed in favor of getting a working generator and distributable gem in place. 
}
  s.email = %q{duskhacker@duskhacker.com}
  s.executables = ["ruby_on_skis"]
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    ".gitignore",
     "README.textile",
     "Rakefile",
     "VERSION",
     "bin/ruby_on_skis",
     "lib/ruby_on_skis/generator.rb",
     "ruby_on_skis.gemspec",
     "sources/Gemfile",
     "sources/Rakefile",
     "sources/bin/init.rb",
     "sources/bin/pinit.rb",
     "sources/config/environment.rb",
     "sources/config/requires.yml",
     "sources/data/depends_1736.csv",
     "sources/data/depends_3092.csv",
     "sources/data/find_libs.rb",
     "sources/data/lorem.txt",
     "sources/fixtures/messages.yml",
     "sources/images/ruby_on_skis.ico",
     "sources/lib/extensions/string/truncate.rb",
     "sources/lib/models/message.rb",
     "sources/lib/wx/app.xrc",
     "sources/lib/wx/app/app_frame.rb",
     "sources/lib/wx/app/message_panel.rb",
     "sources/lib/wx/app/taskbar_icon.rb",
     "sources/lib/wx/base/appframebase.rb",
     "sources/lib/wx/base/messagepanelbase.rb",
     "sources/lib/wx/helpers/app_helper.rb",
     "sources/migrate/20081128200300_init.rb",
     "sources/package/config.yml",
     "sources/package/installer.nsi",
     "sources/package/mswin.rake",
     "sources/package/osx.rake",
     "sources/package/package_lib.rake",
     "sources/script/console",
     "sources/spec/config/environment_spec.rb",
     "sources/spec/extensions/string/truncate_spec.rb",
     "sources/spec/models/message_spec.rb",
     "sources/spec/spec.opts",
     "sources/spec/spec_helper.rb",
     "sources/tasks/database.rake",
     "sources/wxformbuilder_template.fbp"
  ]
  s.homepage = %q{http://github.com/duskhacker/ruby_on_skis}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Provide a starting structure within which to program your wxRuby project}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

