# Include the gems and the versions you want to use here. This file is only used in production,
# when the program is packaged, this file is ignored in favor of what is available in the package.
---
activerecord:    
  require: activerecord
  version: =2.3.4
activesupport:  
  require: activesupport
  version: =2.3.4
sqlite3-ruby:    
  require: sqlite3
  version: =1.2.3
wxruby-ruby19:
  require: wx
  version: =2.0.0
